### ISSUE TITLE
Internal Server Error for `varexists`

### ISSUE THREAD

**Issue by ghost** [Liquipedia/VariablesLua#1]
Using the `varexists` and `var_final` functions leads to the following error message: `Error sending API request: Internal Server Error`.

**Comment by FO-nTTaX** [comment]
At least on my test wiki (MediaWiki 1.28.3) these functions work just fine, I would need some more details in order to try and reproduce this.

**Comment by FO-nTTaX** [comment]
I've used 
```
    local p = {}
    function p.set(frame)
    	mw.ext.VariablesLua.vardefine('test', 'hehe')
    	mw.ext.VariablesLua.vardefine('test2', 'hoho')
    end
    function p.check(frame)
    	local r
    	r = mw.ext.VariablesLua.varexists('test')
    	return r
    end
    function p.final(frame)
    	local r
    	r = mw.ext.VariablesLua.var_final('test2')
    	return r
    end
    return p
```
as module code and called it like
```
    {{#invoke:Vartest|set}}
    {{#invoke:Vartest|check}}
    {{#invoke:Vartest|final}}
```
to get the printout `true hoho`

**Comment by ghost** [comment]
I tried it on _Mediawiki 1.29.2 (Variables 2.4.0)_.
When trying to save a page containing `{{#invoke:Vartest|check}}` I get this error:
```
[d3a8e4918b12ddeae805e857] /index.php?title=Module:Vartest/doc&action=submit Error from line 48 of /home/hydra/public_html/extensions/VariablesLua/Scribunto_LuaVariablesLuaLibrary.php: Call to undefined method ExtVariables::pf_varexists()
```
`var_final` seems to work now and does not throw an error anymore.

**Comment by FO-nTTaX** [comment]
Ah I see, my version of Extension:Variables is older and the function to handle varexists changed its name and signature. That's easy enough to work around though, I'll create a patch.

**Comment by FO-nTTaX** [comment]
Ok can you test what I just pushed maybe?

**Comment by ghost** [comment]
Sorry I'm currently on vacation and can't test it here. I'll let you know in about 1-2 weeks if no one else has tested it by then.

**Comment by FO-nTTaX** [comment]
No worries, I'll just leave the issue opened

**Comment by ghost** [comment]
Ok, I tested it and it works perfectly! Thanks!
