### ISSUE TITLE
Using a number as the variable `name` or `default` leads to an error

### ISSUE THREAD

**Issue by ghost** [Liquipedia/VariablesLua#3]
Seems like there's still an issue with types in the variable name or default value. Using a number here leads to an exception (`[28f928cbfb2f211bc672a543] Exception Caught: PPFrame_DOM::expand: Invalid parameter type`); In the `value` argument in `vardefine` and `vardefineecho` numbers work just fine though.

This could be fixed in two ways:
1. Change `name` and `default` to `tostring( name )` and `tostring( default )`
2. Change all the `libraryUtil.checkTypeMulti( 'var', 1, name, { 'string', 'number' } )` to `libraryUtil.checkType( 'var', 1, name,  'string' )`

**Comment by FO-nTTaX** [comment]
https://github.com/Liquipedia/VariablesLua/commit/ef9be20787d0b69814b50638fa031d2494431cf4 I forced everything to be strings

**Comment by ghost** [comment]
Great! Sry for not noticing earlier, I tested it using `mw.ext.VariablesLua.vardefine`'s `value` and assumed all other args behaved the same way.

**Comment by FO-nTTaX** [comment]
Yeah it is probably due to some of thos using the object version of $parser->setFunctionHook() and some using the more easy one. No worries about opening issues, as long as there's bugs, there's good reasons for them at any rate.
