### ISSUE TITLE
var_table() isn't working with Variables 2.4.1+

### ISSUE THREAD

**Issue by MGChecker** [Liquipedia/VariablesLua#9]
Because Variables 2.4.1+ converted attributes tagged with `@private` to actual private attributes, your try to directly read the Variables table won't work anymore.

Unfortunately, there's no way to fix this without expanding.the API the extension provides for other extensions. An expansion like that isn't currently planned, as it would allow accessing variables you didn't know about, that you shouldn't interfere with. These can be defined by other extensions or manually by users in other transcluded templates.

**Comment by FO-nTTaX** [comment]
Wouldn't getting the variable with this function work? https://github.com/wikimedia/mediawiki-extensions-Variables/blob/master/ExtVariables.class.php#L317

**Comment by FO-nTTaX** [comment]
I guess that won't work anymore. I'm not married to the function, so I might just remove it again. If you plan of making the variables table visible in some way again, let me know though.

**Comment by MGChecker** [comment]
Of course. Sorry for the inconvenience.

**Comment by FO-nTTaX** [comment]
Pushed a new version 1.4.0 that removes the function
